# Generated by Django 5.2.6 on 2025-09-28 15:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashflowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.category",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.status"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.subcategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.type"
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["record_date"], name="ledger_cash_record__827dff_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ledger_cash_status__4d26dc_idx"
                    ),
                    models.Index(
                        fields=["type"], name="ledger_cash_type_id_add5bf_idx"
                    ),
                    models.Index(
                        fields=["category"], name="ledger_cash_categor_bc73c9_idx"
                    ),
                    models.Index(
                        fields=["subcategory"], name="ledger_cash_subcate_4950cc_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0"))),
                        name="amount_gt_0",
                    )
                ],
            },
        ),
    ]
