# Generated by Django 5.2.6 on 2025-09-30 14:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_name_alter_category_type_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.type', verbose_name='Тип'),
        ),
    ]
